@Pyrra.Api_HostAddress = https://localhost:7294

### Cadastrar um usuário novo
POST {{Pyrra.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "teste2@pyrra.com",
  "password": "senha12345",
  "name": "Vitor"
}

### Fazer login
POST {{Pyrra.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "teste@pyrra.com",
  "password": "senha12345"
}

### Acessar rota protegida (troque TOKEN_AQUI pelo token retornado no login)
GET {{Pyrra.Api_HostAddress}}/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQzZjY2NzAxLWMyODEtNDVhNC04OTY1LTg0YmJiODg2YjY3MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3RlQHB5cnJhLmNvbSIsInN1YiI6ImQzZjY2NzAxLWMyODEtNDVhNC04OTY1LTg0YmJiODg2YjY3MyIsImp0aSI6IjVlYmZlMWZmLWZkYjctNDg3OC1iOTI2LTlmZTQ1ZmM2ZWU4NyIsImV4cCI6MTc4NDQzMzExOSwiaXNzIjoiUHlycmEuQXBpIiwiYXVkIjoiUHlycmEuQ2xpZW50In0.ftkxSOQUSaUz1hhI3SpK7ectFj1FwF3-5hKI791Vjp4

### Criar um foco (deve virar Exercicio, peso alto)
POST {{Pyrra.Api_HostAddress}}/api/focos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQzZjY2NzAxLWMyODEtNDVhNC04OTY1LTg0YmJiODg2YjY3MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3RlQHB5cnJhLmNvbSIsInN1YiI6ImQzZjY2NzAxLWMyODEtNDVhNC04OTY1LTg0YmJiODg2YjY3MyIsImp0aSI6ImY0ZTg5MjhhLTlhOWYtNDMxYy05MWMyLWVlYmVjNTY4ZDEzNyIsImV4cCI6MTc4NDU1OTYxMywiaXNzIjoiUHlycmEuQXBpIiwiYXVkIjoiUHlycmEuQ2xpZW50In0.LFT1JybDGEK1ObdErdXJTkOKI4LABlSzTicVMIpGPwU

{
  "name": "treinar na academia"
}

### Criar outro foco (deve virar Hidratacao, peso baixo)
POST {{Pyrra.Api_HostAddress}}/api/focos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQzZjY2NzAxLWMyODEtNDVhNC04OTY1LTg0YmJiODg2YjY3MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3RlQHB5cnJhLmNvbSIsInN1YiI6ImQzZjY2NzAxLWMyODEtNDVhNC04OTY1LTg0YmJiODg2YjY3MyIsImp0aSI6ImY0ZTg5MjhhLTlhOWYtNDMxYy05MWMyLWVlYmVjNTY4ZDEzNyIsImV4cCI6MTc4NDU1OTYxMywiaXNzIjoiUHlycmEuQXBpIiwiYXVkIjoiUHlycmEuQ2xpZW50In0.LFT1JybDGEK1ObdErdXJTkOKI4LABlSzTicVMIpGPwU

{
  "name": "beber agua"
}

### Listar meus focos
GET {{Pyrra.Api_HostAddress}}/api/focos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQzZjY2NzAxLWMyODEtNDVhNC04OTY1LTg0YmJiODg2YjY3MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3RlQHB5cnJhLmNvbSIsInN1YiI6ImQzZjY2NzAxLWMyODEtNDVhNC04OTY1LTg0YmJiODg2YjY3MyIsImp0aSI6ImY0ZTg5MjhhLTlhOWYtNDMxYy05MWMyLWVlYmVjNTY4ZDEzNyIsImV4cCI6MTc4NDU1OTYxMywiaXNzIjoiUHlycmEuQXBpIiwiYXVkIjoiUHlycmEuQ2xpZW50In0.LFT1JybDGEK1ObdErdXJTkOKI4LABlSzTicVMIpGPwU